packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@code-inspector/core': true
  esbuild: true
  node-pty: true
minimumReleaseAgeExclude:
  - 'vite-plugin-global-vars'
  - 'vite-plugin-react-fs-router'
  - '@kazura/*'
  - komekko
